### PR TITLE
Fix/map

### PR DESCRIPTION
**Pull request by sangwonme**
### Resolve bugs in MainAcitivity maps
- fixed showing so many markers : now just drawing the current GPS point. There's no need for drawing all the markers.
- split trajectories : if user has more than two trajectory, split the trajectory (previous version was connecting all points even though it's different trajectory). Now polylines only connect the dots closer than 100m (this value could be changed)

### HistoryAcitivity
- Add loading duration Data w/ given startDate, endDate (implemented in `StepManager`, `LocationManager`)
- Considering server delay, I made (bool) `loading` in `StepManager`, `LocationManager` and (bool) `waiting` in `HistoryActivity`. Data is updated when loading is completed in Manager.
- correcting date duration : if startDate is after endDate, it automatically swap them.

### CODE REVIEW

**Comment by jiku100** [comment]
I find out some bugs. 
1. When I start the application at first, the map shows a different location. It may be a permission bug.
2. While running the application, the trajectory (or camera) doesn't change to its current position.

**Comment by sangwonme** [comment]
All resolved

**Comment by jiku100** [comment]
Some other bugs.
1. When I start the app, the map shows the seoul national university, not my current location. I think it shows the first location saved in location array.
2. When I sign up a new user and start the application, it doesn't zoom in. Please see the below figure.
Screenshot_20230812-154640

**Comment by sangwonme** [comment]
I fixed both issue

1. I found loading was not working properly for new user. This was because the calling timing of nested  `onResponse()`. I resolved by using `boolean loading` and checking if `onResponse()` is done by eventHandler. (Same structure as History Activity loading data).
2. I think calculating zoomRatio is not perfect. Maybe some fine-tuning is required. But before that I'm curious should we have to show all the trajectory by zoom-out. Is it usable? I'm not sure. So, I just fixed zoomRatio as constant value (16.5f)

**Comment by sangwonme** [comment]
1. Could you explain more details about the case? At the [commit](https://github.com/snuhcs-course/project-ta-project/pull/22#:~:text=for%20new%20user-,29a9e17,-Fix%20just%20fixed), I checked same case and there was no problem. Also it is properly working, as I just tested it.

**Pull request merged**
