### PR TITLE
Feat/history

### PR DESCRIPTION
**Pull request by sangwonme**

### CODE REVIEW

**Comment by Wootack** [comment]
Please provide a high-level explanation of your feature implementation. 
It may include a broad explanation of data structure, what the components do, etc.
I am unfamiliar with Android programming, so such information will be very helpful.

**Comment by sangwonme** [comment]
I updated four files.

1. activity_reports.xml : Reports Activity layout (radio button UI added to select daily/weekly/monthly view)
2. ReportAdapter.java : This is for updating RecyclerView (dynamic view to represent dynamic data which is History data)
3. StepHistory.java : Class representing History data. I added totalHistory / dailyHistory / weeklyHistory / mothlyHistory respectively (Map<String(date), List<Int(walk, jog)>>). Currently, it works with dummy data, but it will be linked to the server data later.
4. ReportsActivity.java : Linking all related code files and control view.

**Comment by Wootack** [comment]
* The application should include column names in its report. 
* The date formats of Daily/Weekly/Monthly reports are all different. Please apply the standardized format. I think "YYYY-MM-DD", "YYYY-MM-W#", and "YYYY-MM" will be fine. 
* Please sort the results by date.

**Comment by sangwonme** [comment]
I updated the codes. Sorting data was easily implemented by using TreeMap<> instead of HashMap<>. 

The conflicts are just from the comment I added. So you can manually resolve conflicts in GitHub.

**Comment by eu1jun** [comment]
LGTM. I just changed the week format to represent the first week as W1 and the second week as W2.

**Pull request merged**
